### ISSUE TITLE
Dont connect to Vatsim servers (Vatsim.Fsd.ClientAuth.dll not found)

### ISSUE THREAD

**Issue by kvsystems** [xpilot-project/Pilot-Client#15]
XPilot Client ver: 1.3.23
X-Plane ver: 11.41
.NET ver: 4.7.2
OS: Win 7 (64)

Error:
Can't find this:
C:\Users\Олег\AppData\Local\xPilot\Vatsim.Fsd.ClientAuth.dll

Preview:
![err-xplane](https://user-images.githubusercontent.com/41616963/89265160-8034ef00-d64d-11ea-8d28-1d31238ad267.png)

**Comment by justinshannon** [comment]
Reinstall xPilot and make sure your antivirus isn’t blocking the file when installing.

**Comment by kvsystems** [comment]
I tried it, the problem remained.

The DLL itself is present in the directory.
No antivirus software

**Comment by justinshannon** [comment]
Can you translate the error message to English?

**Comment by kvsystems** [comment]
ok, ok.
The DLL "Vatsim.Fsd.ClientAuth.dll" could not be loaded. The specified module could not be found.
Thought because of the Cyrillic alphabet on the path to the library, but changing the path to "D:\xPilot" also does not solve the problem.

I really look forward to your comments or corrections, the client is very successful.
Thank you very much for your promptness!

**Comment by justinshannon** [comment]
Hi again,

Can you give this version of Vatsim.Fsd.ClientAuth.dll a try? Just unzip it and replace it with the current one in the xPilot app folder.

[Vatsim.Fsd.ClientAuth.dll.zip](https://github.com/xpilot-project/Pilot-Client/files/5030040/Vatsim.Fsd.ClientAuth.dll.zip)

**Comment by kvsystems** [comment]
This file with error.

[Vatsim.Fsd.ClientAuth.With.Err.zip](https://github.com/xpilot-project/Pilot-Client/files/5037222/Vatsim.Fsd.ClientAuth.With.Err.zip)

**Comment by kvsystems** [comment]
With the file that you gave it worked, thanks a lot,
I hope you find the problem in the file from JavaScript ardent hello to C # :)
