### ISSUE TITLE
XPilot client version 1.3.38 crashing unexpectedly

### ISSUE THREAD

**Issue by satviksinha12** [xpilot-project/Pilot-Client#38]
Hello everyone ,I am here to bring to your attention that x plane 11 is crashing because xpilot plugin . Whenever I am starting x Plane 11 and choosing a flight , after done with preloading , the x plane starts crashing, the log files showed that The application has crashed due to pulgin xpilot cllient  1.3.38. Here is my log file
[Log.txt](https://github.com/xpilot-project/Pilot-Client/files/6327157/Log.txt)

**Comment by justinshannon** [comment]
Please don't use GitHub issues for support related questions. I would suggest you join the xPilot Discord for help.
